name: United Charity Football League
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.75241
title: United Charity Football League
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061e31'
    - '#ffffff'
    - '#a6afb5'
    - '#737f89'
    - '#00912b'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
