name: The UCFL
favicon: null
layout_spectrum: 0.24663
typography_spectrum: 0.98862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00912b'
    - '#001327'
    - '#ffffff'
    - '#cfd1df'
    - '#6d6f7d'
  brandStrength: 1
  lightness: 0.9649322903715074
  saturation: 0.6233386492822319
  rhythmicContrast: 0.027821285650134087
purpose: []
