name: United Charity Football League
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.98862
title: United Charity Football League
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1d1d'
    - '#ffffff'
    - '#4d4d4d'
    - '#818181'
    - '#ababab'
  brandStrength: 1
  lightness: 0
  saturation: 0.6233386492822319
  rhythmicContrast: 0.5
purpose: []
